name: Suggestion / idea
description: Lightweight suggestion or idea.
title: "idea: "
labels: ["idea", "needs-triage"]
body:
  - type: input
    id: title-idea
    attributes:
      label: Idea
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      render: markdown
    validations:
      required: true
